require: rubocop-rspec

Style/AlignHash:
  Exclude:
    - spec/**/*

Style/WordArray:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Exclude:
    - spec/**/*

Style/SpaceAroundOperators:
  Exclude:
    - spec/**/*

Style/SpaceInsideHashLiteralBraces:
  Exclude:
    - spec/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
