require: rubocop-rspec

AllCops:
  Exclude:
    - ext/pg_query/extconf.rb
    - vendor/**/*
    - tmp/**/*
    - lib/pg_query/pg_query_pb.rb

Layout/AlignHash:
  Exclude:
    - spec/**/*

Style/WordArray:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Exclude:
    - spec/**/*

Layout/SpaceAroundOperators:
  Exclude:
    - spec/**/*

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - spec/**/*

Performance/RegexpMatch:
  Exclude:
    - ext/pg_query/extconf.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

# extend self preserves private methods,
# module_function buggily removes them.
Style/ModuleFunction:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false
